version: "1.0"
info:
  model: int-scaffold
packages:
- name: PLTAIDemoMCSPProject
  gitServerName: pltaidemorepo
  gitUrl: https://github.com/Bharath-Meka-0058MR744
  gitUsername: Bharath-Meka-0058MR744
  gitBranch: main
services:
- serviceName: project.pltaidemomcsp.integrations:es_updateLoyaltyObjectSF
  packages:
  - name: PLTAIDemoMCSPProject
    version: "1.0"
- serviceName: SalesforceCRMUpdate:updateLoyaltyObject
  packages:
  - name: PLTAIDemoMCSPProject
    version: "1.0"
